# This workflow will build a Kotlin project with Gradle and cache/restore any dependencies to improve the workflow execution time

name: Build & Test FlowForms Core

# Runs on every push to main and every pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradle check task - Build and Test FlowForms-Core
      run: ./gradlew FlowForms-Core:check
        
